# -*- coding: utf-8 -*-
"""Thread_Contador.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-n4edCUWryPNeJ3puEPAEvESWIGIKNpn
"""

import time
from threading import Thread

class Contador(Thread):
    def run(self):
        for i in range(1, 11):
            print(i)
            try:
                time.sleep(1)
            except KeyboardInterrupt:
                print("Thread foi interrompida")

def main():
    print("Hello World!")
    contador = Contador()
    contador.start()
    contador.join()  # Aguarda a thread terminar antes de continuar

if __name__ == "__main__":
    main()