# -*- coding: utf-8 -*-
"""Ex02_ThreadPrioridade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YXyINQGHfgd5g4hXmnesgdj2faFaDjXr
"""

'''
Ex02 - É importante notar que o Python não tem um sistema de prioridade de threads tão explícito quanto o Java.
O módulo threading não permite definir prioridades de threads diretamente. No entanto,
você pode simular esse comportamento ao usar um controle de tempo ou um loop que prioriza
uma thread sobre a outra. '''

import time
from threading import Thread

# Função para a thread de alta prioridade
def thread_alta_prioridade():
    for i in range(10):
        print(f"Thread de Alta Prioridade - Mensagem {i}")
        time.sleep(0.5)  # Pequena pausa para simular trabalho

# Função para a thread de baixa prioridade
def thread_baixa_prioridade():
    for i in range(10):
        print(f"Thread de Baixa Prioridade - Mensagem {i}")
        time.sleep(0.8)  # Pequena pausa para simular trabalho

def main():
    # Cria a thread de alta prioridade
    t1 = Thread(target=thread_alta_prioridade)

    # Cria a thread de baixa prioridade
    t2 = Thread(target=thread_baixa_prioridade)

    # Inicia as threads
    t1.start()
    t2.start()

    # Aguarda ambas as threads terminarem
    t1.join()
    t2.join()

if __name__ == "__main__":
    main()